[package]
name = "rust-actix-web-stub"
version = "0.1.0"
authors = ["Damien Dube <damien.dube@guavus.com>"]
edition = "2018"

[dependencies]
actix-web = "2"
actix-rt = "1"
clap = "2"
serde = "1"
serde_derive = "1.0.92"
toml = "0.5.1"
